//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JezykAngielski.Core.Services {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JezykAngielski.Core.Services.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Testy Cambridge English Qualifications dla dzieci (YLE) stworzono po to, by móc ocenić to, w jakim stopniu dzieci między 7 a 12 rokiem życia opanowały język angielski.
        /// </summary>
        internal static string _1DescNote1 {
            get {
                return ResourceManager.GetString("1DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz zrozumieć i używać często spotykanych wyrażeń i prostych zwrotów, przedstawić siebie i innych, zapytać się o dane osobowe, takie jak: imię, nazwisko, gdzie mieszka, co posiadają, kogo znają itp. Potrafisz się komunikować w prosty sposób, jeśli osoba z którą rozmawiasz mówi wolno i wyraźnie..
        /// </summary>
        internal static string _1DescNote2 {
            get {
                return ResourceManager.GetString("1DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _1DescNote3 {
            get {
                return ResourceManager.GetString("1DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O A1 Elementary.
        /// </summary>
        internal static string _1Note1 {
            get {
                return ResourceManager.GetString("1Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie A1.
        /// </summary>
        internal static string _1Note2 {
            get {
                return ResourceManager.GetString("1Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _1Note3 {
            get {
                return ResourceManager.GetString("1Note3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Egzamin A2 Key to pierwszy z serii egzaminów Cambridge English Qualifications dla dorosłych, który pokazuje, że znasz angielski na podstawowym poziomie. Egzamin A2 Key jest dla tych, którzy mają za sobą około 250 godzin nauki oraz znają angielski w mowie i piśmie na poziomie podstawowym. To pierwszy krok w budowaniu kompetencji językowych dla celów przyszłej kariery lub studiów..
        /// </summary>
        internal static string _2DescNote1 {
            get {
                return ResourceManager.GetString("2DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz zrozumieć podstawowe wyrażenia i zwroty językowe, pisać krótkie i proste notatki lub wiadomości i listy prywatne, w prosty sposób opisać swoją rodzinę, innych ludzi, warunki życia, swoje wykrztałcenie, swoją obecną i poprzednią pracę, radzić sobie w bardzo krótkich rozmowach towarzyskich..
        /// </summary>
        internal static string _2DescNote2 {
            get {
                return ResourceManager.GetString("2DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _2DescNote3 {
            get {
                return ResourceManager.GetString("2DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O A2 Key.
        /// </summary>
        internal static string _2Note1 {
            get {
                return ResourceManager.GetString("2Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie A2.
        /// </summary>
        internal static string _2Note2 {
            get {
                return ResourceManager.GetString("2Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _2Note3 {
            get {
                return ResourceManager.GetString("2Note3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Certyfikat B1 Preliminary pokazuje, że znasz podstawy języka angielskiego i posiadasz praktyczne umiejętności językowe pozwalające komunikować się w codziennych sytuacjach. Podczas przygotowań do egzaminu cały czas uczysz się praktycznego języka i rozwijasz swoje umiejętności językowe.
        /// </summary>
        internal static string _3DescNote1 {
            get {
                return ResourceManager.GetString("3DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz czytać proste teksty pisane i artykóły w języku angielskim, pisać listy i e-maile na codzienne tematy, prowadzić notatki, wyrażać proste opinie i nastroje w mowie i piśmie w języku angielskim..
        /// </summary>
        internal static string _3DescNote2 {
            get {
                return ResourceManager.GetString("3DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _3DescNote3 {
            get {
                return ResourceManager.GetString("3DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O B1 Preliminary.
        /// </summary>
        internal static string _3Note1 {
            get {
                return ResourceManager.GetString("3Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie B1.
        /// </summary>
        internal static string _3Note2 {
            get {
                return ResourceManager.GetString("3Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _3Note3 {
            get {
                return ResourceManager.GetString("3Note3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Certyfikat B2 First potwierdza, że potrafisz posługiwać się używanym na co dzień praktycznym językiem angielskim potrzebnym w pracy lub w nauce. Co roku tysiące osób pragnących poprawić szanse znalezienia pracy i przyjęcia na uczelnię przystępuje do egzaminu B2 First..
        /// </summary>
        internal static string _4DescNote1 {
            get {
                return ResourceManager.GetString("4DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz prowadzić rozmowy w języku angielskim, wyrażając swoje opinie i przezentując różne argumenty, śledzić wiadomości i informacje dotyczące codziennych tematów, pisać w języku angielskim, przedstawiając plusy i minusy różnych punktów widzenia danej sytuacji, uczestniczyć w programach wymiany międzynarodowej między szkołami lub uczelniami, pisać listy, raporty, opowiadania i stosować inne rodzaje wypowiedzi pisemniej, przeprowadzić prezentację w języku angielskim na znane tematy z życia codziennego..
        /// </summary>
        internal static string _4DescNote2 {
            get {
                return ResourceManager.GetString("4DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _4DescNote3 {
            get {
                return ResourceManager.GetString("4DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O B2 First.
        /// </summary>
        internal static string _4Note1 {
            get {
                return ResourceManager.GetString("4Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie B2.
        /// </summary>
        internal static string _4Note2 {
            get {
                return ResourceManager.GetString("4Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _4Note3 {
            get {
                return ResourceManager.GetString("4Note3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ponad 6000 instytucji edukacyjnych, firm i instytucji państwowych na całym świecie uznaje C1 Advanced za potwierdzenie wysoce zaawansowanego poziomu znajomości języka. Przygotowanie do egzaminu C1 Advanced pomaga rozwinąć umiejętności pozwalające czerpać maksymalne korzyści z nauki, pracy oraz życia w krajach anglojęzycznych..
        /// </summary>
        internal static string _5DescNote1 {
            get {
                return ResourceManager.GetString("5DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz studiować w języku angielskim w kraju lub za granicą, efektywnie komunikować się na zaawansowanym poziomie językowym w sytuacjach codziennych, a także w trakcie dyskusji podczas studiów odbywanych w języku angielskim, pracować w środowisku anglojęzycznym, w pełni brać udział w konferencjach, spotkaniach biznesowych i seminariach akademickich, przeprowadzanych w języku angielskim, pisać eseje wyrażające różne punkty widzenia, używając także pojęć astrakcyjnych, śledzić wiadomości i informacje, a ta [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string _5DescNote2 {
            get {
                return ResourceManager.GetString("5DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _5DescNote3 {
            get {
                return ResourceManager.GetString("5DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O C1 Advanced:.
        /// </summary>
        internal static string _5Note1 {
            get {
                return ResourceManager.GetString("5Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie C1.
        /// </summary>
        internal static string _5Note2 {
            get {
                return ResourceManager.GetString("5Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _5Note3 {
            get {
                return ResourceManager.GetString("5Note3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu C2 Proficiency to certyfikat, który jest uznawany jako potwierdzenie znajomości języka angielskiego na poziomie zaawansowania zbliżonym do poziomu rodzimych użytkowników języka przez tysiące wiodących firm i instytucji edukacyjnych na świecie. Przygotowanie się i zdanie egzaminu C2 Proficiency oznacza, że możesz studiować i pracować posługując się językiem angielskim na najwyższym poziomie zaawansowania, na przykład, podczas zagranicznych studiów podyplomowych..
        /// </summary>
        internal static string _6DescNote1 {
            get {
                return ResourceManager.GetString("6DescNote1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potrafisz studiować w języku angielskim na najwyższym poziomie zaawansowania, na przykłąd, podczas studiów podyplomowych czy doktorackich, prowadzić negocjacje biznesowe na poziomie menedżerskim w międzynarodowych kontekstach biznesowych, rozumieć złożone aspekty wielorakich form pisarskich, prowadzić rozmowy wymagające użycia języka obcego na poziomie abstrakcyjnym i emocjonalnym..
        /// </summary>
        internal static string _6DescNote2 {
            get {
                return ResourceManager.GetString("6DescNote2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _6DescNote3 {
            get {
                return ResourceManager.GetString("6DescNote3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O C2 Proficiency:.
        /// </summary>
        internal static string _6Note1 {
            get {
                return ResourceManager.GetString("6Note1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Umiejętności na poziomie C2.
        /// </summary>
        internal static string _6Note2 {
            get {
                return ResourceManager.GetString("6Note2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string _6Note3 {
            get {
                return ResourceManager.GetString("6Note3", resourceCulture);
            }
        }
    }
}
